apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: miru-syslog
  labels:
    app: miru-syslog
spec:
  template:
    metadata:
      labels:
        name: miru-syslog
    spec:
      containers:
        - image: docker.phx1.jivehosted.com/r2e2/miru-syslog:latest
          name: miru-syslog
          command:
            - /go/bin/miru-syslog
          ports:
            - containerPort: 514
              hostPort: 514
              name: syslogtcpport
              protocol: TCP
            - containerPort: 514
              hostPort: 514
              name: syslogudpport
              protocol: UDP
          env:
          - name: MIRU_SYSLOG_HOST_PORT
            value: :514
          - name: MIRU_STUMPTOWN_HOST_PORT
            value: 10.126.5.155:10004
          livenessProbe:
            tcpSocket:
              port: 514
