apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: miru-syslog
  labels:
    app: miru-syslog
spec:
  template:
    metadata:
      labels:
        name: miru-syslog
    spec:
      containers:
        - image: docker.phx1.jivehosted.com/mako/miru-syslog:7d25ac56154d1c7319c6a0743994be2b152f91f6
          name: miru-syslog
          command:
            - /go/bin/miru-syslog
          ports:
            - containerPort: 514
              hostPort: 514
              name: syslogport
            - containerPort: 8081
              hostPort: 8081
              name: adminport
          env:
          - name: MAKO_STATSD_HOST
            value: 127.0.0.1
          - name: MAKO_STATSD_PORT
            value: "8125"
          - name: MAKO_SERVICE_ID
            value: miru-syslog
          - name: MAKO_ENVIRONMENT
            value: mako-dev-test
          - name: MAKO_PIPELINE
            value: main
          - name: MAKO_VERSION
            value: 15713b5b733e11069f68c2b78cbe5ad3e4a40abc
          - name: MIRU_STUMPTOWN_HOST_PORT
            value: :514
          livenessProbe:
            httpGet:
              path: /ping
              port: 8081
